{"name": "Ошибка авторизации при вводе невалидных данных", "status": "passed", "parameters": [{"name": "nonexistent_credentials", "value": "{'login': 'Upon.840', 'password': '$6Z4TqSnt*'}"}], "start": 1739189245311, "stop": 1739189245529, "uuid": "ff07a4c2-6e61-4890-9c45-d4fdd4f8a939", "historyId": "e89afa22eb0ee5cd138bdb5ece478db7", "testCaseId": "46eb53d9fa648330864f3ea6c25e2251", "fullName": "tests.test_login_courier.TestCourierLogin#test_courier_login_invalid_data_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "12AM"}, {"name": "thread", "value": "5788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}