{"name": "Ошибка авторизации при вводе невалидных данных", "status": "passed", "parameters": [{"name": "nonexistent_credentials", "value": "{'login': 'Izam12345', 'password': '1234567'}"}], "start": 1739189245534, "stop": 1739189245729, "uuid": "b7715e57-33fb-47a8-83da-20d79e9f369d", "historyId": "ef4884725be8d9b34cde2c9f51d654ef", "testCaseId": "46eb53d9fa648330864f3ea6c25e2251", "fullName": "tests.test_login_courier.TestCourierLogin#test_courier_login_invalid_data_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "12AM"}, {"name": "thread", "value": "5788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}